
a <- available.packages()
install.packages("devtools")
find.package("devtools")
require(devtools)
install_github("slidify","ramnathv")
install_github("slidifyLibraries", "ramnathv")
library(slidify)
source("http://bioconductor.org/biocLite.R")
biocLite()
biocLite("GenomicFeatures")
library(GenomicFeatures)
library(slidify)
search()
install.packages("ggplot2")
library(ggplot2)
install.packages("KernSmooth")